# Dev build which uses BuildKit for better cache by preventing reinstalling dependencies every time they change
# -> Faster build and startup, allowing a more efficient developement environment. Runs on GPU mode.
# Run with command: 
# `COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose -f docker-compose.yml -f docker-compose.dev.yml up --build`
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend/files:/app/files
      - ./backend/data:/app/data
    environment:
      - LOCAL_AI_ENABLED=true
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
  ai:
    build: ./ai
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    gpus: all

volumes:
  ollama_data: